# Generated by Django 4.1.3 on 2023-02-02 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0002_accounttype_alter_account_account_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatementCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StatementType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_description', models.CharField(max_length=100)),
                ('statement_value', models.FloatField(default=0.0)),
                ('statement_date', models.DateTimeField()),
                ('fowarded', models.CharField(max_length=100)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.account')),
                ('statement_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statement.statementcategory')),
                ('statement_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statement.statementtype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
