# Generated by Django 4.1.3 on 2023-02-02 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='fowarded',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
