# Generated by Django 4.1.3 on 2023-02-07 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statement', '0003_remove_statement_fowarded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='statement_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='statement.statementcategory'),
        ),
    ]
