# Generated by Django 4.1.3 on 2023-02-07 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statement', '0004_alter_statement_statement_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='destiny_account',
            field=models.IntegerField(null=True),
        ),
    ]
