# Generated by Django 4.1.3 on 2023-02-01 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='earning',
            name='total_value',
            field=models.FloatField(default=0.0),
        ),
    ]
